### ISSUE TITLE
error when running 5G Wizard

### ISSUE THREAD

**Issue by rauppvictor** [pyansys/5G-Wizard#1]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Hello dear

When trying to run the 5G Wizard script, some errors are appearing. Could you tell me what could be happening?
I'm using version 2024.1 and my PyAEDT is 0.9.1.
The error is shown below:

File "C:\Users\vraupp\Python\Lib\site-packages\pyaedt\generic\grpc_plugin.py", line 120, in __Invoke__       
    return _retry_ntimes(
           ^^^^^^^^^^^^^^
  File "C:\Users\vraupp\Python\Lib\site-packages\pyaedt\generic\general_methods.py", line 825, in _retry_ntimes
    raise AttributeError("Error in Executing Method {}.".format(function.__name__))
AttributeError: Error in Executing Method InvokeAedtObjMethod.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\vraupp\Estudo\gihub_\5G-Wizard-main\5G_Wizard.py", line 456, in <module>
    myApp = MainWindow(aedtapp)
            ^^^^^^^^^^^^^^^^^^^
  File "d:\vraupp\Estudo\gihub_\5G-Wizard-main\5G_Wizard.py", line 41, in __init__
    self.initGUI()
  File "d:\vraupp\Estudo\gihub_\5G-Wizard-main\5G_Wizard.py", line 48, in initGUI
    project_names = self.gui_params.get_project_names()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\vraupp\Estudo\gihub_\5G-Wizard-main\Lib\Populate_GUI.py", line 15, in get_project_names
    return list(self.aedtapp.odesktop.GetProjectList())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vraupp\Python\Lib\site-packages\pyaedt\generic\grpc_plugin.py", line 133, in DynamicFunc
    return self.__Invoke__(funcName, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vraupp\Python\Lib\site-packages\pyaedt\generic\grpc_plugin.py", line 124, in __Invoke__
    raise GrpcApiError("Failed to execute grpc AEDT command: {}".format(funcName))
pyaedt.generic.general_methods.GrpcApiError: Failed to execute grpc AEDT command: GetProjectList
PS C:\Users\vraupp> 

### 📝 Steps to reproduce

I run the 5G Wizard code in VS Code and the errors appeared instantly.

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2024.1

### 🐍 Which Python version are you using?

3.12

### 📦 Installed packages

```shell
annotated-types==0.7.0
ansys-pythonnet==3.1.0rc3
anyio==4.2.0
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==2.4.1
async-lru==2.0.4
attrs==23.2.0
Babel==2.14.0
beautifulsoup4==4.12.3
bleach==6.1.0
certifi==2023.11.17
cffi==1.16.0
charset-normalizer==3.3.2
clr-loader==0.2.6
colorama==0.4.6
comm==0.2.1
contourpy==1.2.1
cycler==0.12.1
debugpy==1.8.0
decorator==5.1.1
defusedxml==0.7.1
exceptiongroup==1.2.0
executing==2.0.1
fastjsonschema==2.19.1
fonttools==4.52.1
fpdf2==2.7.9
fqdn==1.5.1
h11==0.14.0
h5py==3.11.0
httpcore==1.0.5
httpx==0.27.0
idna==3.6
importlib-metadata==7.0.1
ipykernel==6.29.0
ipython==8.21.0
ipywidgets==8.1.2
isoduration==20.11.0
jedi==0.19.1
Jinja2==3.1.3
json5==0.9.14
jsonpointer==2.4
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.9.0
jupyter-lsp==2.2.2
jupyter_client==8.6.0
jupyter_core==5.7.1
jupyter_server==2.12.5
jupyter_server_terminals==0.5.2
jupyterlab==4.2.1
jupyterlab_pygments==0.3.0
jupyterlab_server==2.27.2
jupyterlab_widgets==3.0.10
kiwisolver==1.4.5
MarkupSafe==2.1.4
matplotlib==3.9.0
matplotlib-inline==0.1.6
mistune==3.0.2
nbclient==0.9.0
nbconvert==7.14.2
nbformat==5.9.2
nest-asyncio==1.6.0
notebook==7.2.0
notebook_shim==0.2.3
numpy==2.0.0
overrides==7.7.0
packaging==23.2
pandocfilters==1.5.1
parso==0.8.3
pillow==10.3.0
platformdirs==4.2.0
plumbum==1.8.3
pooch==1.8.2
prometheus-client==0.19.0
prompt-toolkit==3.0.43
psutil==5.9.8
pure-eval==0.2.2
pyaedt==0.9.1
pycparser==2.21
pydantic==2.7.1
pydantic_core==2.18.2
pyedb==0.11.2
Pygments==2.17.2
pyparsing==3.1.2
PySide6==6.7.2
PySide6_Addons==6.7.2
PySide6_Essentials==6.7.2
python-dateutil==2.8.2
python-json-logger==2.0.7
pyvista==0.43.10
pywin32==306
pywinpty==2.0.12
PyYAML==6.0.1
pyzmq==25.1.2
qtconsole==5.5.2
QtPy==2.4.1
referencing==0.33.0
requests==2.31.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rpds-py==0.17.1
rpyc==6.0.0
Rtree==1.2.0
scipy==1.14.0
scooby==0.10.0
Send2Trash==1.8.2
setuptools==65.5.0
shiboken6==6.7.2
six==1.16.0
sniffio==1.3.0
soupsieve==2.5
stack-data==0.6.3
terminado==0.18.0
tinycss2==1.2.1
toml==0.10.2
tomli==2.0.1
tornado==6.4
traitlets==5.14.1
types-python-dateutil==2.8.19.20240106
typing_extensions==4.9.0
uri-template==1.3.0
urllib3==2.2.0
vtk==9.3.0
wcwidth==0.2.13
webcolors==1.13
webencodings==0.5.1
websocket-client==1.7.0
widgetsnbextension==4.0.10
zipp==3.17.0
```

**Comment by ariensligar** [comment]
@rauppvictor I will need to test this in the current version of pyAEDT and AEDT. This toolkit was built and tested using a much older version of pyAEDT and AEDT

**Comment by rauppvictor** [comment]
Thanks for the quick response @ariensligar.
 We are with a customer trying to use a toolkit and he is having problems.

Please let me know if you have any news.

Thanks again

**Comment by ariensligar** [comment]
@rauppvictor I have made some changes, if you can try the current version. I wasn't able to re-create the exact issue you were having but I did update to more recent version of pyAEDT and tested using AEDT 2024R1.

**Comment by rauppvictor** [comment]
Hello @ariensligar 

I'm going to do some tests. 

The customer would like to get the worst case Power Density graphically considering the different Codebook beams. Is this possible using a script?
He was using the Toolkit tool, but apparently the Power Density graph generated by the tool doesn't show the worst case.

Thanks.

**Comment by ariensligar** [comment]
@rauppvictor 
The output from the toolkit shows max PD for each beam. For example, you can see from this output report, the worst case PD is beam index 2, the PD plot will also be created on this same page for that beam.
![image](https://github.com/ansys/5G-Wizard/assets/61566626/2c2278db-2742-4be3-b300-11b9e4cab843)

**Comment by rauppvictor** [comment]
Hello @ariensligar

I'm have a issue when use the 5G Wizard Toolkit with Codebook using the Paired Beams. Using the attached Codebook file the "PD_Total" graph <fig1.png> is generated. However, the maximum value in this graph does not correspond to the peak power density presented in the "Summary" report. 
If the graph does not represent the worst-case maximum PD, what is being considered in this graph?

I used the AEDT 2024.1 and Array_4_1 simulation example in these testes.

[CodebookExample.csv](https://github.com/user-attachments/files/16097903/CodebookExample.csv)
[PowerDensitySummary_AllBeams_on_5mm_Surface.csv](https://github.com/user-attachments/files/16097912/PowerDensitySummary_AllBeams_on_5mm_Surface.csv)
![fig1](https://github.com/ansys/5G-Wizard/assets/172837849/8d7fbc9d-9617-4ba4-bde5-e5243a88d555)

**Comment by ariensligar** [comment]
These results are not from this toolkit
